[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
impeller-core = { workspace = true }
impeller-hal = { workspace = true }
impeller-hal-vulkan = { workspace = true }
impeller-hal-gles = { workspace = true }
impeller-present-drm = { workspace = true }
impeller-testkit = { workspace = true }
glow = { workspace = true }
