//! Translates the WGSL source tree into the targets each backend needs.
//!
//! One source language, many targets, no C++ shader toolchain: naga emits
//! SPIR-V today and MSL, HLSL, and GLSL for backends that do not exist yet.
//! Translation happens at build time so no shader compiler ships in the
//! runtime and pipeline creation has nothing to parse.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let shader_dir = manifest.join("shaders");

    println!("cargo:rerun-if-changed={}", shader_dir.display());

    let mut generated =
        String::from("// Generated by build.rs from the WGSL sources. Do not edit.\n\n");

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&shader_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", shader_dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "wgsl"))
        .collect();
    // Sorted so the generated file is byte-identical across builds; directory
    // order is not stable and would make the output churn.
    entries.sort();

    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        generated.push_str(&compile(path));
    }

    std::fs::write(out_dir.join("shaders.rs"), generated).expect("writing generated shaders");
}

/// Compile one WGSL file to SPIR-V and emit it as a `&[u32]` constant.
fn compile(path: &Path) -> String {
    let source =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

    let module = naga::front::wgsl::parse_str(&source).unwrap_or_else(|e| {
        // Shader errors are build errors. Emitting a broken module and failing
        // at pipeline creation would report the problem far from its cause.
        panic!("parsing {}:\n{}", path.display(), e.emit_to_string(&source))
    });

    let mut validator = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        // Push constants are how per-draw paint reaches the shader. Without
        // this the validator rejects the declaration rather than the backend
        // failing later, which is the right place for it to be caught.
        naga::valid::Capabilities::PUSH_CONSTANT,
    );
    let info = validator
        .validate(&module)
        .unwrap_or_else(|e| panic!("validating {}: {e}", path.display()));

    let options = naga::back::spv::Options::default();
    let words = naga::back::spv::write_vec(&module, &info, &options, None)
        .unwrap_or_else(|e| panic!("spirv for {}: {e}", path.display()));

    let name = path
        .file_stem()
        .and_then(|s| s.to_str())
        .expect("shader file name")
        .to_uppercase()
        .replace('-', "_");

    let mut out = format!(
        "/// SPIR-V for `{}.wgsl`, with entry points `vs_main` and `fs_main`.\npub static {}_SPV: &[u32] = &[\n",
        path.file_stem().unwrap().to_string_lossy(),
        name
    );
    for chunk in words.chunks(8) {
        out.push_str("    ");
        for w in chunk {
            out.push_str(&format!("{w:#010x}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
    out
}
