//! Translates the WGSL source tree into the targets each backend needs.
//!
//! One source, several targets: SPIR-V for Vulkan and GLSL ES for GLES today,
//! with MSL and HLSL available for backends that do not exist yet. The point is
//! not merely convenience — it is that both backends render from the same
//! source, so a shader change cannot land on one and miss the other.
//!
//! One source language, many targets, no C++ shader toolchain: naga emits
//! SPIR-V today and MSL, HLSL, and GLSL for backends that do not exist yet.
//! Translation happens at build time so no shader compiler ships in the
//! runtime and pipeline creation has nothing to parse.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let shader_dir = manifest.join("shaders");

    println!("cargo:rerun-if-changed={}", shader_dir.display());

    let mut generated =
        String::from("// Generated by build.rs from the WGSL sources. Do not edit.\n\n");

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&shader_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", shader_dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "wgsl"))
        .collect();
    // Sorted so the generated file is byte-identical across builds; directory
    // order is not stable and would make the output churn.
    entries.sort();

    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        generated.push_str(&compile(path));
    }

    std::fs::write(out_dir.join("shaders.rs"), generated).expect("writing generated shaders");
}

/// Compile one WGSL file to SPIR-V and emit it as a `&[u32]` constant.
fn compile(path: &Path) -> String {
    let source =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

    let module = naga::front::wgsl::parse_str(&source).unwrap_or_else(|e| {
        // Shader errors are build errors. Emitting a broken module and failing
        // at pipeline creation would report the problem far from its cause.
        panic!("parsing {}:\n{}", path.display(), e.emit_to_string(&source))
    });

    let mut validator = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        // Push constants are how per-draw paint reaches the shader. Without
        // this the validator rejects the declaration rather than the backend
        // failing later, which is the right place for it to be caught.
        naga::valid::Capabilities::PUSH_CONSTANT,
    );
    let info = validator
        .validate(&module)
        .unwrap_or_else(|e| panic!("validating {}: {e}", path.display()));

    let options = naga::back::spv::Options::default();
    let words = naga::back::spv::write_vec(&module, &info, &options, None)
        .unwrap_or_else(|e| panic!("spirv for {}: {e}", path.display()));

    let name = path
        .file_stem()
        .and_then(|s| s.to_str())
        .expect("shader file name")
        .to_uppercase()
        .replace('-', "_");

    let mut out = format!(
        "/// SPIR-V for `{}.wgsl`, with entry points `vs_main` and `fs_main`.\npub static {}_SPV: &[u32] = &[\n",
        path.file_stem().unwrap().to_string_lossy(),
        name
    );
    for chunk in words.chunks(8) {
        out.push_str("    ");
        for w in chunk {
            out.push_str(&format!("{w:#010x}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n\n");

    // GLSL ES needs one source per stage, unlike SPIR-V where both entry
    // points live in one module.
    for (stage, entry, suffix) in [
        (naga::ShaderStage::Vertex, "vs_main", "VS_GLSL"),
        (naga::ShaderStage::Fragment, "fs_main", "FS_GLSL"),
    ] {
        let glsl = force_std140(write_glsl(&module, &info, stage, entry, path), path, stage);
        out.push_str(&format!(
            "/// GLSL ES 300 for `{}.wgsl`, {} stage.\npub static {}_{}: &str = r####\"{}\"####;\n\n",
            path.file_stem().unwrap().to_string_lossy(),
            entry,
            name,
            suffix,
            glsl
        ));
    }

    out
}

/// Give the paint's uniform block an explicit `std140` layout.
///
/// A uniform block with no layout qualifier is `shared`, which means the
/// driver chooses where each member sits and a caller is expected to ask.
/// This side writes the bytes itself, so it needs a layout that is specified
/// rather than reported -- and `std140` is the one every implementation
/// agrees on.
///
/// naga would write the qualifier itself, but only alongside an explicit
/// binding, and GLSL ES 3.00 has no `layout(binding = )` for a uniform block;
/// that arrived in 3.10, which is above this project's floor. So it is added
/// here.
///
/// Editing generated source is worth doing carefully rather than avoiding: the
/// declaration is located exactly, the count is asserted, and a translator that
/// emits a different shape fails the build here instead of producing a shader
/// whose members are read from wherever the driver put them. The snapshot test
/// pins the same output from the other side.
fn force_std140(glsl: String, path: &Path, stage: naga::ShaderStage) -> String {
    const DECLARATION: &str = "\nuniform Paint_block_";
    // Only the fragment stage reads the paint, and a translator emits a global
    // only into the stages that use it -- so the vertex stage having one would
    // mean the shader changed, not the translation.
    let want = usize::from(stage == naga::ShaderStage::Fragment);
    let found = glsl.matches(DECLARATION).count();
    assert_eq!(
        found,
        want,
        "{} {stage:?}: expected {want} unqualified paint block(s) to qualify, found {found}. \
         Either the translator's output changed shape or a stage started reading the paint; \
         qualify what is actually there rather than dropping this.",
        path.display()
    );
    glsl.replace(DECLARATION, "\nlayout(std140) uniform Paint_block_")
}

/// Translate one entry point to GLSL ES 300.
fn write_glsl(
    module: &naga::Module,
    info: &naga::valid::ModuleInfo,
    stage: naga::ShaderStage,
    entry: &str,
    path: &Path,
) -> String {
    let options = naga::back::glsl::Options {
        version: naga::back::glsl::Version::Embedded {
            version: 300,
            is_webgl: false,
        },
        ..Default::default()
    };
    let pipeline = naga::back::glsl::PipelineOptions {
        shader_stage: stage,
        entry_point: entry.to_string(),
        multiview: None,
    };

    let mut out = String::new();
    let mut writer = naga::back::glsl::Writer::new(
        &mut out,
        module,
        info,
        &options,
        &pipeline,
        naga::proc::BoundsCheckPolicies::default(),
    )
    .unwrap_or_else(|e| panic!("glsl writer for {} {stage:?}: {e}", path.display()));
    writer
        .write()
        .unwrap_or_else(|e| panic!("glsl for {} {stage:?}: {e}", path.display()));
    out
}
