[package]
name = "impeller-hal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
publish.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Rendering hardware abstraction layer for impeller-rs."
keywords = ["hal", "graphics", "vulkan", "gles", "renderer"]
categories = ["graphics", "rendering::graphics-api"]

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
