[package]
name = "impeller-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
glam = { workspace = true }
impeller-geometry = { workspace = true }
impeller-hal = { workspace = true }
impeller-renderer = { workspace = true }

[dev-dependencies]
impeller-hal-vulkan = { workspace = true }
impeller-hal-gles = { workspace = true }
