[package]
name = "impeller-present-vk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Vulkan WSI swapchain presentation target for impeller-rs."
keywords = ["vulkan", "wsi", "swapchain", "presentation"]
categories = ["graphics", "rendering::graphics-api"]

[dependencies]
ash = { workspace = true }
impeller-core = { workspace = true }
impeller-hal = { workspace = true }
impeller-hal-vulkan = { workspace = true }
impeller-present = { workspace = true }
