[package]
name = "impeller-hal-vulkan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
publish.workspace = true
license.workspace = true
repository.workspace = true
description = "Vulkan rendering backend for impeller-rs."
keywords = ["vulkan", "backend", "graphics", "renderer", "hal"]
categories = ["graphics", "rendering::graphics-api"]

[lints]
workspace = true

[dependencies]
ash = { workspace = true }
gpu-allocator = { workspace = true }
impeller-hal = { workspace = true }
impeller-shaders = { workspace = true }

[dev-dependencies]
impeller-present = { path = "../impeller-present" }
rustix = { version = "1.1.4", default-features = false, features = ["event", "std"] }
