[package]
name = "impeller-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
publish.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Drawing API for impeller-rs: Canvas, Paint, Color, recording and execution."
keywords = ["canvas", "renderer", "graphics", "2d", "paint"]
categories = ["graphics", "rendering"]

[lints]
workspace = true

[dependencies]
half.workspace = true
glam = { workspace = true }
impeller-geometry = { workspace = true }
impeller-hal = { workspace = true }
impeller-renderer = { workspace = true }
impeller-text = { workspace = true }
